### ISSUE TITLE
2.00TB equals to 2.99TB, just change one line will fix this bug

### ISSUE THREAD

**Issue by HarleyTan** [go-ponder/meter#1]
hi,thx for your good job!

example
`	value, _ := meter.ParseBytes("2.000 TB")
	fmt.Println(	value,"\t",meter.HumanSize(value))

	value, _ = meter.ParseBytes("2.99 TB")
	fmt.Println(	value,"\t",meter.HumanSize(value))
`

just change meter.go line 147 
before:
`*b = ByteSize(uint64(val) * unit)`
after
`*b = ByteSize(val * float64(unit))`

will fix this bug

**Comment by thinkgos** [comment]
@HarleyTan  you are right ,thank you!

**Comment by thinkgos** [comment]
@HarleyTan new tag @v0.0.9 fix this bug. thanks again
